/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.malbino.gui;

import java.util.List;
import org.malbino.daos.CategoriaDao;
import org.malbino.gui.tablemodels.TableModelCategoria;
import org.malbino.models.Categoria;

/**
 *
 * @author Tincho
 */
public class Categorias extends javax.swing.JInternalFrame {
    
    CategoriaDao categoriaDao;

    /**
     * Creates new form categorias
     */
    public Categorias() {
        initComponents();
        
        categoriaDao = new CategoriaDao();
        
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    public void actualizarLista() {
        List<Categoria> listaCategorias = categoriaDao.listaCategorias();
        TableModelCategoria tableModelCategoria = new TableModelCategoria(listaCategorias);
        jTable1.setModel(tableModelCategoria);

        jTable1.getColumnModel().getColumn(1).setMinWidth(400); //nombre
        jTable1.getColumnModel().getColumn(2).setMinWidth(200); //observaciones
    }
    
    public void nuevaCategoria() {
        Categoria categoria = new Categoria("", "");
        categoriaDao.nuevaCategoria(categoria);
        
        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Categorias");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/malbino/img/nuevo.png"))); // NOI18N
        jButton1.setText("Nueva Categoria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nuevaCategoria();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
